apiVersion: v1
kind: Service
metadata:
  name: aks-demo
  namespace: practice-aks
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: aks-demo
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000